config/routes.rb
Studium::Application.routes.draw do
  devise_for :users
  
  # Set the root
  root 'home#index'

  # About page
  get '/about', to: 'home#about', as: :about

  # Readings resource
  resources :readings, except: [:new, :show], shallow: true   do
    # Redirect to sections#index instead of readings#show (which is not valid)
    get '/:reading_id/', to: 'sections#index', on: :collection
    
    # Sections resource
    resources :sections, except: [:show], shallow: true do
      # Render sections#notes instead of sections#show (which is not valid)
      get '/', to: 'sections#notes', on: :member
      # Add route to sections#notes
      get '/notes', to: 'sections#notes', on: :member
      # Match PATCH/PUT /notes to sections#update_notes
      match '/notes', to: 'sections#update_notes', on: :member, via: [:put, :patch]
      
      get '/test', to: 'sections#test', on: :member
      # Questions resource
      resources :questions, shallow: true, except: [:show, :new]
    end

  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  # Associations
  belongs_to :section

  # Validations
  validates :title, presence: true, length: {within: 1..160}
  validates :answer, length: {maximum: 1600}

  validates :section, presence: true

  # Instance methods
  def answered?
    !self.answer.nil? && !self.answer.strip.empty?
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  layout "sections"

  before_action :authenticate
  before_action :authorize
  before_action :get_layout_variables

  def index
    @section = Section.find(params[:section_id])
    @questions = @section.questions.order("created_at")
    
    check_pjax
  end

  def create
    strong_params = params.require(:question).permit(:title)
    @question = Question.new strong_params
    @question.section_id = params[:section_id]

    if @question.save
      redirect_to section_questions_path(params[:section_id])
    else
      @questions = @question.section.questions.order("created_at")
      render 'index'
    end
  end

  def edit
    @question = Question.find params[:id]
    check_pjax
  end

  def update
    strong_params = params.require(:question).permit(:title, :answer)
    @question = Question.find params[:id]

    if @question.update(strong_params)
      redirect_to section_questions_path(@question.section), 
      notice: "Question \"#{@question.title}\" successfully updated"
    else
      render 'edit'
    end
  end

  def destroy
    @question = Question.find params[:id]
    @question.destroy

    redirect_to section_questions_path(@section)
  end

  private

  def authenticate
    redirect_to new_user_session_path   unless user_signed_in?
  end

  def authorize
    section = Section.find_by(id: params[:section_id])
    question = Question.find_by(id: params[:id])
    
    section_condition = section &&  section.reading.user.id == current_user.id
    question_condition = question &&  question.section.reading.user.id == current_user.id

    unless section_condition || question_condition
      redirect_to readings_path
    end
  end

  def get_layout_variables
    @section = Section.find params[:section_id] || Question.find(params[:id]).section
    @reading = @section.reading
    @sections = @reading.sections.order("created_at")
  end
  
  def check_pjax
    if request.headers['X-PJAX']
      render layout: false
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_errors.html.slim
- if question && !question.errors.empty?
  .alert.alert-danger
    ul
      - question.errors.each do |field, message|
        li = "#{field} #{message}"

app/views/questions/_new_question.html.slim
.panel.panel-default
  .panel-heading  Create New Question
  .panel-body
    = render partial: 'errors', locals: {question: @question}

    = form_for(question || Question.new, html: {role: 'form', class: 'horizontal-form'}, 
      url: section_questions_path(section)) do |f|
      
      .form-group
        .col-xs-8.col-sm-9.col-md-10
          = f.text_field :title, {class: 'form-control', placeholder: 'What is your question?'}
        
        .col-xs-4.col-sm-3.col-md-2
          = f.submit 'Create', {class: 'btn btn-primary'}

app/views/questions/_questions_list.html.slim
#questions-list.panel-group
  - questions.each do |question|
    .panel(class="#{question.answered? ? 'panel-success' : 'panel-default'}")
      .panel-heading
        a(href="#collapse-#{question.id}" data-toggle="collapse" data-parent="#questions-list")  = question.title

        span.btn-group
          = link_to 'Edit', edit_question_path(question), class: 'btn btn-warning'
          = link_to 'Delete', question, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

      div(id="collapse-#{question.id}" class="panel-collapse collapse")
        .panel-body
          = question.answer

app/views/questions/edit.html.slim
= render partial: 'sections/heading', locals: {section: @section, selected: :questions}
br

= link_to "\u2190 Back to Questions", section_questions_path(@section.id)

h3  
  | Edit Question: 
  strong = @question.title

= render partial: 'errors', locals: {question: @question}
br

= form_for(@question, html: {role:'form', class: 'form'}) do |f|
  .form-group
    = f.label :title, 'Title', {class: 'control-label'}
    = f.text_field :title, {class: 'form-control'}

  .form-group
    = f.label :answer, 'Answer', {class: 'control-label'}
    = f.text_area :answer, {class: 'form-control', rows: 5}

  = f.submit 'Save', {class: 'btn btn-warning'}

app/views/questions/index.html.slim
= render partial: 'sections/heading', locals: {section: @section, selected: :questions}
br

= render partial: 'new_question', locals: {section: @section, question: @question}
br

= render partial: 'questions_list', locals: {questions: @questions}