config/routes.rb
Studium::Application.routes.draw do
  devise_for :users
  
  # Set the root
  root 'home#index'

  # About page
  get '/about', to: 'home#about', as: :about

  # Readings resource
  resources :readings, except: [:new, :show], shallow: true   do
    # Redirect to sections#index instead of readings#show (which is not valid)
    get '/:reading_id/', to: 'sections#index', on: :collection
    
    # Sections resource
    resources :sections, except: [:show], shallow: true do
      # Render sections#notes instead of sections#show (which is not valid)
      get '/', to: 'sections#notes', on: :member
      # Add route to sections#notes
      get '/notes', to: 'sections#notes', on: :member
      # Match PATCH/PUT /notes to sections#update_notes
      match '/notes', to: 'sections#update_notes', on: :member, via: [:put, :patch]
      
      get '/test', to: 'sections#test', on: :member
      # Questions resource
      resources :questions, shallow: true, except: [:show, :new]
    end

  end
end

app/views/shared/_footer.html.slim
footer
    small
      | Studium is a personal project/experimental app. 
      br
      | Developed by 
      a href="http://www.github.com/rsalgado" Roberto Salgado. 
      | 2014.

app/views/shared/_header.html.slim
/Top Navbar
nav.navbar.navbar-inverse role="navigation"
  .navbar-header
    /Brand
    = link_to 'Studium', root_path, {class: 'navbar-brand'}

    /Toggleable navigation button
    button.navbar-toggle(type="button" data-toggle="collapse" data-target="#studium-navbar")
      /Three-bar icon
      span.icon-bar
      span.icon-bar
      span.icon-bar

  #studium-navbar.collapse.navbar-collapse
    /Right-side links (and dropdown)
    ul.nav.navbar-nav.navbar-right
      li
        = link_to 'About', about_path

      - if user_signed_in?
        /User session dropdown
        li.dropdown
          a.dropdown-toggle(data-toggle="dropdown" href="#")
            = current_user.email
            b.caret
          ul.dropdown-menu
            li
              = link_to 'Settings', edit_user_registration_path
            li.divider
            li
              = link_to 'Sign Out', destroy_user_session_path, method: :delete
      
      - else
        li
          = link_to 'Sign up', new_user_registration_path
        li
          = link_to 'Sign in', new_user_session_path

app/views/shared/_sections.html.slim
/ Requires locals: sections, current_section, reading_id

.col-xs-4
  .panel.panel-info
    .panel-heading  Sections
    .panel-body
      / Create new section area
      .new-section-area
        = link_to 'Add New Section', new_reading_section_path(reading_id),
            {class: 'btn btn-info btn-block btn-lg'}
      / Sections List
      ul.nav.nav-pills.nav-stacked
        - sections.each do |section|
          li(class="#{ (current_section && current_section.id == section.id) ? 'active': '' }")
            = link_to section.name, section