config/routes.rb
Studium::Application.routes.draw do
  devise_for :users
  
  # Set the root
  root 'home#index'

  # About page
  get '/about', to: 'home#about', as: :about

  # Readings resource
  resources :readings, except: [:new, :show], shallow: true   do
    # Redirect to sections#index instead of readings#show (which is not valid)
    get '/:reading_id/', to: 'sections#index', on: :collection
    
    # Sections resource
    resources :sections, except: [:show], shallow: true do
      # Render sections#notes instead of sections#show (which is not valid)
      get '/', to: 'sections#notes', on: :member
      # Add route to sections#notes
      get '/notes', to: 'sections#notes', on: :member
      # Match PATCH/PUT /notes to sections#update_notes
      match '/notes', to: 'sections#update_notes', on: :member, via: [:put, :patch]
      
      get '/test', to: 'sections#test', on: :member
      # Questions resource
      resources :questions, shallow: true, except: [:show, :new]
    end

  end
end

app/models/section.rb
class Section < ActiveRecord::Base
  # Associations
  belongs_to :reading
  has_many :questions, dependent: :destroy

  # Validations
  validates :notes, length: {maximum: 12000}
  validates :name, presence: true, length: {within: 1..160}
  
  validates :reading, presence: true
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :authenticate
  before_action :authorize
  before_action :find_reading_and_sections, only: [:index, :new, :create]

  def index
  end

  def new
    @section = Section.new
    @section.reading = @reading
  end

  def create
    strong_params = params.require(:section).permit(:name)
    @section = Section.new strong_params
    @section.reading = @reading

    if @section.save
      redirect_to reading_sections_path(@reading)
    else
      render 'new'
    end
  end

  def edit
    @section = Section.find params[:id]
    @reading = @section.reading
    @sections = @reading.sections.order("created_at")
    check_pjax
  end

  def update
    strong_params = params.require(:section).permit(:name)
    @section = Section.find params[:id]

    if @section.update(strong_params)
      redirect_to @section, notice: "#{@section.name} succesfully updated"
    else
      @reading = @section.reading
      @sections = @reading.sections.order("created_at")
      render 'edit'
    end
  end

  def destroy
    @section = Section.find params[:id]
    @section.destroy
    redirect_to reading_sections_path(@section.reading)
  end


  def notes
    @section = Section.find params[:id]
    @reading = @section.reading
    @sections = @reading.sections.order("created_at")

    check_pjax
  end

  def update_notes
    strong_params = params.require(:section).permit(:notes)
    @section = Section.find params[:id]

    if @section.update(strong_params)
      redirect_to notes_section_path(@section)
    else
      @reading = @section.reading
      @sections = @reading.sections.order("created_at")
      render 'notes'
    end
  end
  
  def test
    @section = Section.find params[:id]
    @answered_questions = @section.questions.select(&:answered?)
    @reading = @section.reading
    @sections = @reading.sections.order("created_at")
    check_pjax
  end

  private

  def authenticate
    redirect_to new_user_session_path  unless user_signed_in?
  end

  def authorize
    reading = Reading.find_by(id: params[:reading_id])
    section = Section.find_by(id: params[:id])
    
    reading_condition = reading && reading.user.id == current_user.id
    section_condition = section &&  section.reading.user.id == current_user.id

    unless reading_condition || section_condition
      redirect_to readings_path
    end
  end

  def find_reading_and_sections
    @reading = Reading.find params[:reading_id]
    @sections = @reading.sections.order("created_at")
  end
  
  def check_pjax
    render layout: false   if request.headers['X-PJAX']
  end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_errors.html.slim
- if section && !section.errors.empty?
  .alert.alert-danger
    ul
    - section.errors.each do |field, message|
        li = "#{field} #{message}"

app/views/sections/_heading.html.slim
/ Requires locals: section, selected

/ Header
h2 
  | #{section.name} 
  span.btn-group
    = link_to 'Edit', edit_section_path(section), {class: 'btn btn-warning'}
    = link_to 'Delete', section, {method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' }

br

/ Tabs
ul.nav.nav-tabs.nav-justified
  li(class="#{'active' if selected == :notes}") = link_to 'Notes', notes_section_path(section)
  li(class="#{'active' if selected == :questions}") = link_to 'Questions', section_questions_path(section)
  li(class="#{'active' if selected == :test}") = link_to 'Test', test_section_path(section.id)

app/views/sections/edit.html.slim
h3  
 | Edit 
 strong = @section.name

= render partial: 'errors', locals: {section: @section}
br

= form_for(@section, html: {class: 'form', role:'form'}) do |f|
  .form-group
    = f.label :name, 'Name', {class: 'control-label'}
    = f.text_field :name, {class: 'form-control input'}

  .form-group
    = f.submit 'Save', {class: 'btn btn-warning'}

app/views/sections/index.html.slim
.jumbotron
  h2 Here is where you manage your sections
  p On the left, you might:
  ul
    li Add a New Section
    li Select an existing section, and make notes and questions on it

app/views/sections/new.html.slim
h3  Add New Section

/ TODO: Move this to a partial view
/ Errors section 
= render partial: 'errors', locals: {section: @section}

= form_for(@section, html: {role: 'form', class: 'form'}, 
    url: reading_sections_path(@reading) ) do |f|
  
  .form-group
    = f.label :name, 'Name', {class: 'control-label'}
    = f.text_field :name, {class: 'form-control input', placeholder: 'Section Name'}

  = f.submit 'Create', {class: 'btn btn-primary'}

app/views/sections/notes.html.slim
/ Show heading (header and tabs)
= render partial: 'heading', locals: {section: @section, selected: :notes}
br

= render partial: 'errors', locals:{section: @section}
br

/ Notes contents
= form_for(@section, url: notes_section_path(@section), remote: true,
    html: { class: 'form', role: 'form' }  ) do |f|
  .form-group
    = f.label :notes, 'Notes', {class: 'control-label'}
    = f.text_area :notes, {class: 'form-control', id: 'summernote'}

  .form-group
    = f.submit 'Save', {class: 'btn btn-primary pull-right', id: 'save-notes'}

app/views/sections/test.html.slim
= render partial: 'heading', locals: {section: @section, selected: :test}
br

#questions-list.panel-group
  - @answered_questions.each do |question|
    .panel.panel-default
      .panel-heading
        a(data-no-turbolink href="#collapse-#{question.id}" data-toggle="collapse" data-parent="#questions-list")  = question.title

      div(id="collapse-#{question.id}" class="panel-collapse collapse")
        .panel-body
          textarea.test-answer.form-control(placeholder="Your answer")
          .original-answer  
            h4 Click to see your original answer
            p = question.answer

          .question-buttons        
            button.btn.btn-success.done Done!
            button.btn.btn-danger.reset Reset