config/routes.rb
Studium::Application.routes.draw do
  devise_for :users
  
  # Set the root
  root 'home#index'

  # About page
  get '/about', to: 'home#about', as: :about

  # Readings resource
  resources :readings, except: [:new, :show], shallow: true   do
    # Redirect to sections#index instead of readings#show (which is not valid)
    get '/:reading_id/', to: 'sections#index', on: :collection
    
    # Sections resource
    resources :sections, except: [:show], shallow: true do
      # Render sections#notes instead of sections#show (which is not valid)
      get '/', to: 'sections#notes', on: :member
      # Add route to sections#notes
      get '/notes', to: 'sections#notes', on: :member
      # Match PATCH/PUT /notes to sections#update_notes
      match '/notes', to: 'sections#update_notes', on: :member, via: [:put, :patch]
      
      get '/test', to: 'sections#test', on: :member
      # Questions resource
      resources :questions, shallow: true, except: [:show, :new]
    end

  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Studium</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<div class="contents">
  <%= render partial: 'shared/header' %>
  
  <% if notice %>
    <div class="notice alert alert-info"><%= notice %></div>
  <% end %>
  <% if alert %>
    <div class="alert alert-danger"><%= alert %></div>
  <% end %>
  
  <% if content_for?(:subtemplate) %>
    <%= yield(:subtemplate) %>
  <% else %>
    <%= yield %>
  <% end %>

  <div class="params">
  <% if Rails.env.development? %>
    <%= debug params %>
  <% end %>
  </div>

  <%= render 'shared/footer' %>
</div>

</body>
</html>

app/views/layouts/sections.html.slim
/ Custom subtemplate (nested layout)
- content_for(:subtemplate) do
  .contents-area
    = link_to "\u2190 Back to Readings", readings_path
    h1 #{@reading.title}

    .row
      / Sections Area
      = render  partial: 'shared/sections',
                locals: { sections: @sections, current_section: @section, reading_id: @reading.id }
      
      / Current Section Area
      .col-xs-8
        .panel.panel-default
          .panel-body
            #section-contents
              = yield


/ Main template (layout)
= render template: 'layouts/application'